server:
  port: 9090

spring:
  config:
    import:
      - common.yml
      - datasource/datasource-dev.yml
      - aws-parameterstore:/ilsang/backend_dev
  # JPA
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100

  # Redis
  data:
    redis:
      host: ${.elastic_cache_endpoint}
      port: ${.elastic_cache_port}
      useSsl: true

#lgging
logging:
  level:
    root: DEBUG
#    org.springframework: DEBUG
#    com.your.package: DEBUG


multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/

ec2:
  host: ${.ec2_host}
  port: ${.ec2_port}

oauth:
  aos:
    google:
      client-id: 702150906844-l4mc5liud2nt5qi04n4dfsqc6epve4t2.apps.googleusercontent.com
  ios:
    google:
      client-id: 654001951429-ne4ev00taadiag4tr4euigqlv3jgkvr8.apps.googleusercontent.com
    apple:
      client-id: com.ilsang240615.dev
