server:
  port: 9091

spring:
  config:
    import: common.yml, datasource/datasource-prd.yml

  # JPA
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      default_batch_fetch_size: 100


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/
