server:
  port: 9090
  profile: local

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 500KB

file:
  upload-dir: ${user.dir}/src/main/resources/images/