server:
  port: 9091

spring:
  config:
    import:
      - common.yml
      - datasource/datasource-prd.yml
      - aws-parameterstore:/ilsang/backend_prd

  # JPA
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      default_batch_fetch_size: 100

  # Redis
  data:
    redis:
      host: ${.elastic_cache_endpoint}
      port: ${.elastic_cache_port}
      useSsl: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/

ec2:
  host: ${.ec2_host}
  port: ${.ec2_port}

oauth:
  aos:
    google:
      client-id: 702150906844-l4mc5liud2nt5qi04n4dfsqc6epve4t2.apps.googleusercontent.com
  ios:
    google:
      client-id: 702150906844-g5jvs1fm6u1j1rfnvptkoe4eraak2uk9.apps.googleusercontent.com
    apple:
      client-id: com.ilsang240615
  token:
    timeout:
      access-token: 72
      refresh-token: 168
