server:
  port: 9091

spring:
  config:
    import: config-dev.yml

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${matq.database.endpoint}:${matq.database.port}/matq
    username: ${matq.database.username}
    password: ${matq.database.password}

    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 500KB

file:
  upload-dir: ${matq.file.upload-dir}
