server:
  port: 9092

spring:
  config:
    import: common.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${rds.database.endpoint}:${rds.database.port}/matq
    username: ${rds.database.username}
    password: ${rds.database.password}

    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # JPA
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/
