server:
  port: 9091
  profile: dev

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/
