server:
  port: 9090

spring:
  config:
    import: common.yml, datasource/datasource-dev.yml

  # JPA
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100


  # redis
  data:
    redis:
      port: ${elastic-cache.port}
      endpoint: ${elastic-cache.endpoint}


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

multipart:
  max-upload-size: 100KB

file:
  upload-dir: /images/
