apiProject:
  version: V.1.2.0-202412231321

spring:
  config:
    import: aws/rds-info.yml, aws/s3-info.yml , aws/ec2-info.yml, aws/elasticcache-info.yml

  batch:
    jdbc:
      initialize-schema: always
