apiProject:
  version: V.1.2.0-202501072115

spring:
  config:
    import:
      - 'aws-parameterstore:/ilsang/backend_${spring.profiles.active}'

  batch:
    jdbc:
      initialize-schema: always

cloud:
  bucket:
    name: ilsang-bucket-1
