spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 2024-08-23 dev용 DB를 연결. (prd와 분리함.)
    url: jdbc:mysql://${rds.prd.database.endpoint}:${rds.prd.database.port}/${rds.prd.database.schema}
    username: ${rds.prd.database.username}
    password: ${rds.prd.database.password}

    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true