name: CI Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create aws-info file
        run: |
          mkdir -p src/main/resources/aws
          echo "${{ secrets.RDS_INFO }}" > src/main/resources/aws/rds-info.yml
          echo "${{ secrets.S3_INFO }}" > src/main/resources/aws/s3-info.yml
          
      - name: Build with Gradle
        run: ./gradlew build

  merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge PR branch into target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}

      - name: Close PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          gh pr close ${{ github.event.pull_request.number }} --comment "Automatically closed after merging."