name: Deploy On PR to Main

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar

      - name: Create JAR file
        run: |
          mkdir -p build/libs
          cp build/libs/*.jar myapp.jar

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem

      - name: Add known host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy jar to remote server
        run: |
          scp -i ~/private-key.pem myapp.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:bin
          echo "Copied files to remote server"