name: Deploy On PR to Main

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create aws-info file
        run: |
          mkdir -p src/main/resources/aws
          echo "${{ secrets.RDS_INFO }}" > src/main/resources/aws/rds-info.yml
          echo "${{ secrets.S3_INFO }}" > src/main/resources/aws/s3-info.yml

      - name: Create JAR file
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar
          mkdir -p build/libs
          cp build/libs/*.jar apiProject.jar

      - name: Backup jar on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
            if [ -f /bin/apiProject.jar ]; then
              cp -a bin/apiProject.jar backup/apiProject_$TIMESTAMP.jar
              echo "complete backup jar to /home/apiProject_$TIMESTAMP.jar"
            fi

      - name: Copy jar to remote server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          target: bin
          source: apiProject.jar

      - name: Execute deploy script on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 프로세스 종료
            PIDS=$(ps -ef | grep 'java -jar' | grep 'apiProject.jar' | awk '{print $2}')
            if [ -n "$PIDS" ]; then
              echo "Killing existing processes: $PIDS"
              kill -9 $PIDS
            fi

            # 새로운 프로세스 시작
            nohup java -jar /bin/apiProject.jar -Dspring.profiles.active=dev > /dev/null 2>&1 &
            nohup java -jar /bin/apiProject.jar -Dspring.profiles.active=local > /dev/null 2>&1 &